### PR TITLE
docs: emphasize multiple Python versions in Features

### LINKED ISSUE #491: Emphasize compatibility with different Python versions/platforms in Features of README

### PR DESCRIPTION
**Pull request by huxuan**
Fix #491 

----
📚 Documentation preview 📚: https://ss-python--530.org.readthedocs.build/en/530/

### CODE REVIEW

**Review by msclock — APPROVED** [review]
Feels some sense of repeatition🤣

**Comment by huxuan** [comment]
> Feels some sense of repeatition🤣

Actually, I have same feeling, too. Any ideas?

**Comment by msclock** [comment]
> > Feels some sense of repeatition🤣
> 
> Actually, I have same feeling, too. Any ideas?

I consider this is a part of v0.1.0 and a WIP status. so no problem with it.

**Comment by huxuan** [comment]
> I consider this is a part of v0.1.0 and a WIP status. so no problem with it.

OK, in case there is any better ideas for the documentation, feel free to send a pull request directly.

**Pull request merged**
