### PR TITLE
chore: fix Python 3.8 compatibility issue

### PR DESCRIPTION
**Pull request by huxuan**
----
📚 Documentation preview 📚: https://ss-python--368.org.readthedocs.build/en/368/

### CODE REVIEW

**Comment by huxuan** [comment]
@msclock This is the best solution I can come up with for the back compatibility hack.

It will install pre-commit 3.5.0 for Python 3.8 and will install the latest version for Python 3.9 and higher. Besides, the latest version is pinned and can be updated with renovate while the version 3.5.0 is pinned forever.

**Comment by msclock** [comment]
> @msclock This is the best solution I can come up with for the back compatibility hack.
> 
> It will install pre-commit 3.5.0 for Python 3.8 and will install the latest version for Python 3.9 and higher. Besides, the latest version is pinned and can be updated with renovate while the version 3.5.0 is pinned forever.
> 
> Any comments are welcome. :-)

Emm..., I consider the command without the pinned version `pipx install pre-commit` can dramatically reduce the implementation complexity.🤣

**Comment by huxuan** [comment]
> Emm..., I consider the command without the pinned version `pipx install pre-commit` can dramatically reduce the implementation complexity.🤣

That is the state before renovate integration but may not be best practice. Since we enabled the build cache, no pinned version will be treated as cache hit even when a new version released.

**Comment by msclock** [comment]
> > Emm..., I consider the command without the pinned version `pipx install pre-commit` can dramatically reduce the implementation complexity.🤣
> 
> That is the state before renovate integration but may not be the best practice. Since we enabled the build cache, no pinned version will be treated as cache hit even when a new version released.

I see the multiple phase build cache silences the update of pre-commit.

**Review by msclock — APPROVED** [review]

**Pull request merged**
