### PR TITLE
chore: change repo_host_type to repo_platform

### PR DESCRIPTION
**Pull request by huxuan**
----
📚 Documentation preview 📚: https://ss-python--533.org.readthedocs.build/en/533/

### CODE REVIEW

**Comment by msclock** [comment]
BTW, this change makes jinja conditional judgment easier, and I would follow thoes changes to ss-cpp.😀

**Comment by msclock** [comment]
I've done reviewing. If we have no problem with my suggestion, I will pass it an approval.

**Comment by huxuan** [comment]
> I've done reviewing. If we have no problem with my suggestion, I will pass it an approval.

Hi msclock, I did not see any review comments, maybe you forget to send it out? Let me know if I nissed anything.

**Comment by huxuan** [comment]
Just a note, we should mention supporting different platforms in Features.

**Review by msclock — CHANGES_REQUESTED** [review]
I forget to submit reviewed changes.😰

**Comment by huxuan** [comment]
> If we have no problem with my suggestion

Good cache, buddy~ Changed as suggested.

**Review by msclock — APPROVED** [review]

**Pull request merged**
